import svgbuilding from '../../images/svg-building.svg'
// import svgbusiness from '../../images/svg-business.svg'
// import svgemail from '../../images/svg-email.svg'
import svgsuperwoman from '../../images/svg-superwoman.svg'

export const aboutObjOne = {
    id:'about',
    to: 'skills',
    whitebg: true,
    whiteText: false,
    whiteTextSub: false,
    topLine: '',
    headLine: "Hello.\nWelcome again.",
    description: "My name is Jay. A self-taught web developer.\nAs of January 2020, I finished my master's program in Economics and business management.\nThen, on January 2021 I started self-teaching front-end web development.",
    buttonLabel: 'View skills',
    gridStart: false,
    img: svgbuilding,
    alt:'business',
    small:'true',
    primary: 'true',
    secondary:'',
    white:'',
    fontbig: 'true',
    whitehover:'true',
}
export const aboutObjTwo = {
    id:'skills',
    to:'projects',
    whitebg: false,
    whiteText: true,
    whiteTextSub: true,
    topLine: 'Self-teaching web developer',
    headLine: 'Lorem Ipsum is simply dummy text.',
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    buttonLabel: 'View projects',
    gridStart: true,
    img: svgsuperwoman,
    alt:'business',
    small:'true',
    primary: '',
    secondary:'true',
    white:'true',
    fontbig: 'true',
    whitehover:'true',
}
// export const aboutObjThree = {
//     id:'about',
//     whitebg: true,
//     whiteText: false,
//     whiteTextSub: false,
//     topLine: 'The best websites',
//     headLine: 'Choose your favorate theme styles here',
//     description: 'If none of those match your preference. No worries, We got more for you, click the button right below.',
//     buttonLabel: 'Get started',
//     gridStart: false,
//     img: svgbusiness,
//     alt:'business',
//     small:'true',
//     primary: 'true',
//     secondary:'',
//     white:'',
//     fontbig: 'true',
//     whitehover:'true',
// }
// export const aboutObjFour = {
//     id:'about',
//     whitebg: false,
//     whiteText: true,
//     whiteTextSub: true,
//     topLine: 'The best websites',
//     headLine: 'Choose your favorate theme styles here',
//     description: 'If none of those match your preference. No worries, We got more for you, click the button right below.',
//     buttonLabel: 'Get started',
//     gridStart: true,
//     img: svgemail,
//     alt:'business',
//     small:'true',
//     primary: '',
//     secondary:'true',
//     white:'true',
//     fontbig: 'true',
//     whitehover:'true',
// }